import '@fontsource/material-icons'
import '@fontsource/roboto'
import '@mdi/font/css/materialdesignicons.min.css'
import 'react-toggle/style.css'
import './src/styles/global.css'
import './src/styles/index.scss'
// import 'antd/dist/antd.dark.css'
// import 'antd/dist/antd.compact.css'
import 'firebase/auth'
import 'firebase/firestore'
import 'firebase/functions'
