export const notes = [
  'h3 Username',
  'nick.l@sconsults.net',
  'nick.l@auxworld.net',
  'r951236958@gmail.com',

  'h3 2019-05-27',
  'https://www.edx.org/course/data-analysis-with-python',
  'https://www.edx.org/micromasters/mitx-statistics-and-data-science',
  'https://www.edx.org/course/probability-the-science-of-uncertainty-and-data-0',
  'https://www.udemy.com/acl-for-audit-data-analysis-and-visualization/',

  'h3 2019-05-23',
  'https://www.techiediaries.com/angular-httpclient/',
  'https://angular.io/guide/http',
  'https://github.com/johnpapa/angular-tour-of-heroes/blob/master/src/app/hero.service.ts',
  'https://www.vojtechruzicka.com/practicing-coding-interview-pramp/',
  'https://triplebyte.com/users/start',
  'https://akkadia.org/drepper/cpumemory.pdf',
  'https://leetcode.com/',

  'h3 2019-05-17',
  'https://itnext.io/partial-reactive-form-with-angular-components-443ca06d8419',

  'h3 2019-05-16',
  'https://angular.io/guide/reactive-forms',
  'https://stackblitz.com/angular/rdnxrplmkbn',
  '',

  'h3 2019-05-15',
  'https://medium.freecodecamp.org/48-answers-on-stack-overflow-to-the-most-popular-angular-questions-52f9eb430ab0',
  'https://github.com/microsoft/code-push',
  'https://dzone.com/articles/why-we-shound-not-use-function-inside-angular-temp',
  '',

  'h3 2019-05-13',
  'https://coursetro.com/posts/code/171/Angular-7-Tutorial---Learn-Angular-7-by-Example',
  'https://angular.io/api/common/DatePipe',
  'https://material-components.github.io/material-components-web-catalog/#/',
  'https://material-theme-builder.glitch.me/',
  'https://reallifemag.com/numbers-game/',
  'https://codepen.io/myf/',
  'https://codepen.io/bjankord/pen/gzBoWp',
  'https://codepen.io/bertdida/',
  'https://medium.freecodecamp.org/bet-you-cant-solve-this-google-interview-question-4a6e5a4dc8ee',
  'https://trustedsource.org/sources/index.pl',
  'http://atomicdesign.bradfrost.com/table-of-contents/',
  'https://books.google.com.my/books?id=2OCKrF6YNKEC&pg=PR22&dq=%22You+know,+I+couldn%27t+do+it.+I+couldn%27t+reduce+it+to+the+freshman+level.+That+means+we+really+don%27t+understand+it.%22&hl=en&sa=X&redir_esc=y#v=onepage&q=%22You%20know%2C%20I%20couldn%27t%20do%20it.%20I%20couldn%27t%20reduce%20it%20to%20the%20freshman%20level.%20That%20means%20we%20really%20don%27t%20understand%20it.%22&f=false',
  '',
  '',
  '',
  '',

  'h3 2019-05-10',
  'https://juretriglav.si/open-source-collaborative-text-editors/',
  'https://ckeditor.com/docs/ckeditor5/latest/builds/guides/quick-start.html',
  'https://atlaskit.atlassian.com/',
  'https://prosemirror.net/',
  'http://substance.io/texture/',
  'https://www.adamhyde.net/html-word-processors/',
  'https://gitlab.coko.foundation/wax/wax-prosemirror',
  'https://medium.com/tensorflow/introducing-tensorflow-js-machine-learning-in-javascript-bf3eab376db',
  'https://medium.com/tensorflow/introducing-tensorflow-graphics-computer-graphics-meets-deep-learning-c8e3877b7668',
  'https://www.singhkays.com/blog/its-time-replace-gifs-with-av1-video/',
  'https://enlight.nyc/projects/neural-network/',
  'https://slatestarcodex.com/2019/05/07/5-httlpr-a-pointed-review/',
  'https://ivanceras.github.io/svgbob-editor/',
  'https://shaderlab.mgz.me/',
  'https://www.theatlantic.com/science/archive/2018/04/the-myth-of-learning-styles/557687/',
  'https://medium.com/@the_jennitaur/how-to-do-nothing-57e100f59bbb',
  'https://nfrechette.github.io/2019/05/08/sign_flip_optimization/',
  'http://ai.googleblog.com/2019/05/an-end-to-end-automl-solution-for.html',
  'https://blog.iconfactory.com/2019/05/what-to-expect-from-marzipan/',
  '',
  '',

  'h3 2019-05-09',
  'https://lgtm.com/blog/ghostscript_CVE-2018-19134_exploit',
  'https://digest.bps.org.uk/2017/01/19/a-little-discussed-effect-of-therapy-it-changes-your-personality/',
  'https://www.nationalgeographic.com/science/2019/05/tectonic-plate-peeled-apart-could-shrink-atlantic-ocean-geology/',
  'https://classic.minecraft.net/?join=BDnfj4dbWpFsn43g',
  'http://forums.xkcd.com/viewtopic.php?t=16899#p472686',

  'h3 2019-05-08',
  'https://www.twilio.com/blog/a-http-headers-for-the-responsible-developer',
  'https://developers.googleblog.com/2019/05/Flutter-io19.html',
  'https://mathics.github.io/',

  'h3 2019-05-07',
  'https://zerospeech.com/2019/',
  'https://jmperezperez.com/fostering-web-performance-culture/',
  'https://react-coursebuilder.netlify.com',
  'https://www.deconstructoroffun.com/blog/2018/2/27/u6ap146ff5rkmm7fj1qzuhggp395l4',
  'https://plato.stanford.edu/entries/other-minds/',
  'http://acypher.com/wwid/',
  'http://lea.verou.me',
  '',

  'h3 2019-05-06',
  'https://projecteuclid.org/download/pdf_1/euclid.ss/1009213726',
  'https://uxdesign.cc/a-comprehensive-and-honest-list-of-ux-clich%C3%A9s-96e2a08fb2e9',
  'https://startbootstrap.com/themes',
  'https://kazzkiq.github.io/balloon.css',
  'https://codepen.io/FezVrasta',
  'https://raulgrell.github.io/tetris/',

  'h3 2019-04-29',
  'https://www.tonic.ai/post/3-ways-to-nail-your-demo-data',
  'https://tympanus.net/Tutorials/scroll-transitions-webgl',
  'https://rallyinteractive.com',
  'http://www.datastuff.tech/data-science/3-machine-learning-books-that-helped-me-level-up-as-a-data-scientist',

  'h3 2019-04-26',
  'https://www.textbook.ds100.org',
  'http://sangaline.com/post/reverse-engineering-the-hacker-news-ranking-algorithm/',

  'h3 2019-04-24',
  'http://read.gov/aesop/025.html',

  'h3 2019-04-23',
  'https://www.techiediaries.com/angular-tutorial-reactive-forms',
  'https://codepen.io/GuiHS1/pen/BExeWz',
  'https://codepen.io/enlcxx/pen/vmadQz',
  'https://codepen.io/hbuchel/pen/qOxGzW',
  'https://codepen.io/Reklino/pen/raRaXq',
  'https://angular.io/guide/dynamic-form',
  'https://smartcar.com/blog/how-otonomo-is-cloning-our-product',
  'https://medium.com/frontend-fun/angular-introduction-to-internationalization-i18n-28226a85e04e',
  'https://angular.io/guide/i18n',
  '',

  'h3 2019-04-22',
  'https://gurov.github.io/stupid-rss-reader/#/home/https:%2F%2Fxkcd.com%2Frss.xml',
  'https://github.com/gurov/stupid-rss-reader',
  'http://quirkss.com/2019/03/09/retrospective-angularjs/',
  'https://hackernoon.com/angular-digest-26-january-7-march-bd973e55196f',
  'https://yabwe.github.io/medium-editor/',
  'https://ngreact.github.io/ngReact/#examples',
  'https://www.techiediaries.com/angular-course',
  'https://dev.to/irosthebeggar/publishing-websites-at-home-44d3',
  'https://storybook.js.org/docs/guides/guide-angular/',
  'https://github.com/astorfi/Deep-Learning-Roadmap',
  'https://www.fastcompany.com/40563811/dont-tell-recruiters-these-things-if-you-want-the-job',
  'https://yellrobot.com/pony-ai-driverless-cars-guangzhou-china-ponypilot',
  'https://www.reddit.com/r/reactjs/comments/94xxys/embedding_react_app_inside_an_angular_app',
  'https://coursetro.com/posts/code/171/Angular-7-Tutorial---Learn-Angular-7-by-Example',

  'h3 2019-04-19',
  'https://www.sitepoint.com/the-cicada-principle-and-why-it-matters-to-web-designers',
  'https://www.sitepoint.com/examples/primes/lego.html',
  'https://graphemica.com/%E2%98%B0',
  'https://speakerdeck.com/lottejackson/css-current-soon-someday',

  'h3 2019-04-16',
  'http://evincarofautumn.blogspot.com/2012/02/why-concatenative-programming-matters.html',
  'https://www.w3schools.com/colors/colors_names.asp',
  'https://techcrunch.com/2019/04/13/how-do-startups-actually-get-their-content-marketing-to-work/',
  'https://zaff.netlify.com/blog-v0.1.0/',
  'https://news.ycombinator.com/item?id=19503666',
  'https://www.designsystems.com/5-steps-for-including-motion-design-in-your-system/',
  '',

  'h3 2019-04-12',
  'https://godotengine.org',
  'https://en.wikipedia.org/wiki/Seven-dimensional_cross_product',
  'https://www.fast.ai/2018/07/23/auto-ml-3/#goog',
  'http://nlp.fast.ai/#transfer',

  'h3 Bash script for indexing files',
  'https://articles.forensicfocus.com/2013/04/23/ks-an-open-source-bash-script-for-indexing-data/',
  'http://scripts4cf.sourceforge.net/tools.html',
  'https://nannibassetti.com/',
  'http://scripts4cf.sourceforge.net/tools/ks2.2.zip',
  'h3 tar.gz file for size optimization',
  'https://betterexplained.com/articles/how-to-optimize-your-site-with-gzip-compression/',
  'h3 Rivescript: Chat bot',
  'https://www.rivescript.com/try',
  'https://cdnjs.cloudflare.com/ajax/libs/rivescript/2.0.0/rivescript.min.js',
  'h3 Greensock: html5 animation library',
  'https://greensock.com/gsap',
  'https://cdnjs.com/libraries/gsap',
  'h3 BonsaiJS: Graphics library (SVG) - MIT license',
  'http://bonsaijs.org/',
  'https://cdnjs.com/libraries/bonsai',
  'http://www.uxebu.com/',
  'https://github.com/uxebu/bonsai',
  'h3 Nvidia AI turns sketches into photorealistic landscapes in seconds',
  'https://techcrunch.com/2019/03/18/nvidia-ai-turns-sketches-into-photorealistic-landscapes-in-seconds/',
  'https://www.nvidia.com/research/inpainting/selection',
  'https://www.nvidia.com/en-us/research/ai-playground/',
  'h3 Enabling long path in Windows 10',
  'https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/',
  'h3 Medium: How to Deliver Constructive Feedback in Difficult Situations #communication',
  'https://medium.dave-bailey.com/the-essential-guide-to-difficult-conversations-41f736e63ccf',
  'h3 Font library',
  'https://fonts.google.com',
  'https://fontlibrary.org/',
  'https://www.google.com/get/noto/',
  'h3 Digital fonts (monospaced)',
  'https://fontlibrary.org/en/font/layla-digital',
  'https://fontlibrary.org/en/font/segment7',
  'https://fontlibrary.org/en/font/lcd',
  'https://fontlibrary.org/en/font/mnicmp',
  'https://fontlibrary.org/en/font/keypunch029',
  'https://fontlibrary.org/en/font/threefourtwotwo',
  'https://fontlibrary.org/en/font/lovematrix',
  'h3 Sentiment Analysis',
  'http://www.kaikaichen.com/?p=539',
  'http://thiagomarzagao.com/resources',
  'https://www.quora.com/How-much-does-LexisNexis-Factiva-Proquest-etc-cost',
  'h3 CCAT',
  'https://www.criteriacorp.com/resources/ccat_prep.php',
  'https://jobflare.com/test-prep/?utm_medium=referral&utm_source=Criteria_Candidates&utm_campaign=Candidates',
  'h3 Tatham Games',
  'https://www.chiark.greenend.org.uk/~sgtatham/puzzles/',
  'h3 Puzzler',
  'https://puzzling.stackexchange.com/users/50778/el-guest',
  'h3 Excel',
  'https://www.extendoffice.com/documents/excel/649-excel-remove-spaces.html',
]